# Generated by Django 5.1 on 2024-09-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to='blog.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'verbose_name': 'Лайк/Дизлайк к комментарию',
                'verbose_name_plural': 'Лайки/Дизлайки к комментариям',
                'constraints': [models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_comment_like_dislike')],
            },
        ),
        migrations.CreateModel(
            name='LikeDislikePaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to='blog.paste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'verbose_name': 'Лайк/Дизлайк к пасте',
                'verbose_name_plural': 'Лайки/Дизлайки к пасте',
                'constraints': [models.UniqueConstraint(fields=('user', 'paste'), name='unique_user_paste_like_dislike')],
            },
        ),
    ]
