# Generated by Django 5.1 on 2024-09-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedislikecomment',
            options={'verbose_name': 'Рейтинг коментария', 'verbose_name_plural': 'Рейтинг коментариев'},
        ),
        migrations.AlterModelOptions(
            name='likedislikepaste',
            options={'verbose_name': 'Рейтинг пасты', 'verbose_name_plural': 'Рейтинг пасты'},
        ),
    ]
