# Generated by Django 5.1.1 on 2024-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_messages_author_remove_notifications_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[(1, 'Comment'), (2, 'Like'), (3, 'Dislike'), (4, 'Favourite')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
