# Generated by Django 5.1.1 on 2024-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_notifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Comment'), (2, 'Like'), (3, 'Dislike'), (4, 'Favourite')], max_length=1),
        ),
    ]
