# Generated by Django 5.1.1 on 2024-10-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
