services:
  django:
    build:
      context: ./pastebin
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static_volume:/vol/web/static
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/vol/web/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django

  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery_worker:
    build:
      context: ./pastebin
      dockerfile: celery_worker.dockerfile
    env_file: .env
    depends_on:
      - django
      - redis

  celery_beat:
    build:
      context: ./pastebin
      dockerfile: celery_beat.dockerfile
    env_file: .env
    depends_on:
      - django
      - redis

volumes:
  pgdata:
  static_volume:
