services:
  web:
    container_name: pastebin
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
  

  db:
    container_name: postgres_container
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis_container
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker_container
    build: .
    command: celery -A config worker --loglevel=info --pool=solo
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery_beat:
    container_name: celery_container
    build: .
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  pg_data: