# Generated by Django 5.1 on 2024-09-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'verbose_name': 'Подписка на тег',
                'verbose_name_plural': 'Подписки на теги',
                'constraints': [models.UniqueConstraint(fields=('user', 'tag'), name='unique_user_tag_subscription')],
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.customuser')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Подписка на пользователя',
                'verbose_name_plural': 'Подписки на пользователей',
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed'), name='unique_follower_followed')],
            },
        ),
    ]
