# Generated by Django 5.1.1 on 2024-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='content',
        ),
        migrations.AddField(
            model_name='paste',
            name='access_status',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Draft')], default=1),
        ),
        migrations.AddField(
            model_name='paste',
            name='content_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paste',
            name='is_delete_after_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paste',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paste',
            name='time_live',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
