# Generated by Django 5.1.6 on 2025-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='syntax',
            field=models.CharField(choices=[('plaintext', 'Обычный текст'), ('python', 'Python'), ('javascript', 'JavaScript'), ('htmlmixed', 'HTML'), ('markdown', 'Markdown'), ('xml', 'XML'), ('clike', 'C/C++/Java'), ('sql', 'SQL'), ('css', 'CSS'), ('yaml', 'YAML')], default='plaintext', max_length=20),
        ),
    ]
