# Generated by Django 5.1.1 on 2024-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_paste_content_url_paste_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='time_live',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
