# Generated by Django 5.1.1 on 2024-09-25 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_paste_time_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
