# Generated by Django 5.1.1 on 2024-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_paste_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
