# Generated by Django 5.1.1 on 2024-10-01 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_paste_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='time_live',
            field=models.DurationField(blank=True, choices=[(None, 'Никогда'), (datetime.timedelta(seconds=3600), 'Через 1 час'), (datetime.timedelta(days=1), 'Через 1 день'), (datetime.timedelta(days=7), 'Через 1 неделю')], null=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='views_count',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
